### ISSUE TITLE
Player Rotation

### ISSUE THREAD

**Issue by MintBlast** [selgesel/godot-third-person-controller#2]
Hi, I have a problem with the player rotation based on the tutorial you've provided. I have also checked the source code from this repository for reference, the problem persisted. The code for the rotation you've provided was:

`# if the player has any amount of movement, lerp the player model's rotation towards the current
    # movement direction based on its angle towards the X+ axis on the XZ plane
    if _move_dir != Vector2.ZERO:
        _rotation = lerp_angle(_rotation, atan2(-direction.x, -direction.z), turn_speed * delta)
        _skin.rotation.y = _rotation`

What I did was:
`if _move_dir != Vector2.ZERO:
		_rotation = lerp_angle(_rotation, atan2(-_move_dir.x, -_move_dir.z), turn_speed * delta)
		_skin.rotation.y = _rotation`

This is the code I have followed from both the tutorial and the source code but the error in my editor says: "Can't get index 'z' on base Vector2."

Could it be that it uses Vector2? Your method provided on the video works for you but doesn't work for me. Did I miss something in the code tutorial and/or the source code provided??

While I am at it, I'll also check and observe carefully the code I wrote based on you and fix the issue while I can.

Thanks

**Comment by selgesel** [comment]
Hey, so I think the problem is caused by the `atan2(-_move_dir.x, -_move_dir.z)` part, which uses the move direction (as retrieved by the controls node) and not the `direction`. 

It's true that `_move_dir` is a `Vector2` and does not have a `z` component, but even if we were to use the `y` component we wouldn't get the correct angle because `_move_dir` is an unrotated `Vector2` that points in one of the 8 major directions. The `xz` components of the `direction` vector is essentially the same vector, but on 3D space, and rotated in the Y axis by the camera's current rotation in the Y axis.

Using `_move_dir` in the if expression and `direction` inside the statement might be a little confusing, but since we manipulate the `y` component of the `direction` vector to add gravity or jump force, we can't rely on its equality to `Vector3.ZERO` to check for any horizontal movement.

I quickly sketched up this horrible drawing but I hope it helps :)

![move-dir-vs-direction](https://user-images.githubusercontent.com/89156904/154424189-26b0c9da-1dab-47a3-b29a-46cd54178a40.png)

**Comment by MintBlast** [comment]
Hi,

What I could do is provide 3 directions. My theory that I've made is: 
`_rotation = lerp_angle(_skin.rotation.y, atan2(-_move_dir.x, -_move_dir.z), turn_speed * delta)`
There's a same 3rd person controller tutorial provided from rayuse rp 

Instead of using Vector2 I used Vector 3 instead and it will work from there. The problem is the use of operand types since both Vector2 and Vector3 are invalid to != from the code you've provided. I'm quite new to GDScript so I don't know what I'm doing from here.

Apart from that **should I just make a node with the controls script** provided just like what you have in your repository?

**Comment by selgesel** [comment]
Hey, as I said, `_move_dir` is a separate vector that indicates the player's input, but `direction` is the actual direction of the movement, and we have to use `direction` to get the correct rotation e.g.

```gdscript
_rotation = lerp_angle(_rotation, atan2(-direction.x, -direction.z), turn_speed * delta)
```

...or if you want to change the skin's rotation directly,

```gdscript
_skin.rotation.y = lerp_angle(_skin.rotation.y, atan2(-direction.x, -direction.z), turn_speed * delta)
```

Besides keeping separate vectors, I also suggest using a `Vector2` for the movement direction vector (aka  `_move_dir`) because I think it's more intuitive that way. It's also worth noting that with Godot 4 comes a method called `get_vector()` that returns a vector based on the given input strengths, and that method also returns a `Vector2`.

As for whether or not to make a separate node for the controls it's really up to you, but I like the concept of separation of concerns, and over the course of my 11+ years of professional programming career I've witnessed countless occasions where it helped achieve a more robust and manageable codebase.

That said, I also believe it should only be done if it actually does make sense, and only when the programmer(s) is/are familiar enough with the codebase and the environment they're working in (which is Godot in this case). Otherwise it just adds an unnecessary level of complexity that both the current and future programmers have to tackle.

For instance, when this repo first started the input code was located inside the player script and it stayed that way for the next video (see the [0.0.1](https://github.com/selgesel/godot-third-person-controller/blob/0.0.1/player/Player.gd) and [0.0.2](https://github.com/selgesel/godot-third-person-controller/blob/0.0.2/player/Player.gd) versions).

With the latest version, however, I added lots of new functionality to the controls script, and since I knew it would make it much more to maintain the player script in the long run if I were to leave them all in, I moved them all to a new node. And nevertheless, it's grown considerably, and I surely wouldn't want [all this code](https://github.com/selgesel/godot-third-person-controller/blob/0.0.3/player/Controls.gd) to be inside the player script any longer (not to mention the scene tree updates that are necessary to support touch screen input).

So ultimately, I do recommend making a new node for the controls script, but only when you feel it's absolutely necessary, and if you're confident/happy with the change overall :)

**Comment by MintBlast** [comment]
Ok, so I started everything again and it just magically worked out of the blue. Probably because I had the node controls script but I've already done this during my first attempt then again I don't know since I'm a complete newbie. 🤷‍♂️

The only problem I have is the movement but I'll have to inspect the code a little bit more and see what's wrong. 

Thanks again for the help <3.

**Comment by selgesel** [comment]
Oh that's great! I'm really happy to see that it all worked out in the end. Please don't refrain from opening further issues if you have any questions.

Happy hunting!
